In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df=pd.read_csv('/content/drive/MyDrive/ai project /sound_blocks/preprocessing data.csv')
df

Unnamed: 0        f0        f1        f2        f3        f4  target
0              0  1.081172 -7.120204  0.680698  0.753853  0.287723       1
1              1  0.959863 -6.558257  0.661967  0.766074  0.287658       1
2              2  0.885624 -6.590372  0.676322  0.770636  0.287718       1
3              3  0.907701 -6.995509  0.668329  0.753980  0.287320       1
4              4  0.844454 -6.508078  0.654847  0.761404  0.287131       1
...          ...       ...       ...       ...       ...       ...     ...
9510        7335  1.275672 -2.170918  0.492680  0.681460  0.284750       3
9511        7336  1.290434 -0.585534  0.520101  0.724953  0.282635       3
9512        7337  1.163247 -0.428505  0.533896  0.717561  0.281436       3
9513        7338  1.324318 -1.359741  0.522031  0.704803  0.284642       3
9514        7339  1.731660 -0.616292  0.550700  0.716718  0.284426       3

[9515 rows x 7 columns]

In [ ]:
df.drop(columns=df.columns[0],axis=1,inplace=True);
df

f0        f1        f2        f3        f4  target
0     1.081172 -7.120204  0.680698  0.753853  0.287723       1
1     0.959863 -6.558257  0.661967  0.766074  0.287658       1
2     0.885624 -6.590372  0.676322  0.770636  0.287718       1
3     0.907701 -6.995509  0.668329  0.753980  0.287320       1
4     0.844454 -6.508078  0.654847  0.761404  0.287131       1
...        ...       ...       ...       ...       ...     ...
9510  1.275672 -2.170918  0.492680  0.681460  0.284750       3
9511  1.290434 -0.585534  0.520101  0.724953  0.282635       3
9512  1.163247 -0.428505  0.533896  0.717561  0.281436       3
9513  1.324318 -1.359741  0.522031  0.704803  0.284642       3
9514  1.731660 -0.616292  0.550700  0.716718  0.284426       3

[9515 rows x 6 columns]

In [ ]:
#type(df)
df.shape
X=df[['f0','f1','f2','f3','f4']]
y=df['target']

In [ ]:
X = X.to_numpy()

In [ ]:
type(X)

numpy.ndarray

In [ ]:
X.reshape(-1,5)

array([[ 1.08117235, -7.12020445,  0.6806978 ,  0.75385284,  0.28772255],
       [ 0.95986348, -6.5582571 ,  0.66196656,  0.766074  ,  0.28765817],
       [ 0.88562375, -6.59037209,  0.6763221 ,  0.77063632,  0.28771833],
       ...,
       [ 1.16324663, -0.42850453,  0.53389639,  0.71756053,  0.28143615],
       [ 1.32431757, -1.35974145,  0.52203089,  0.70480287,  0.28464224],
       [ 1.73166049, -0.61629182,  0.55070013,  0.71671802,  0.28442608]])

In [ ]:
X.shape

(9515, 5)

In [ ]:
X=X.reshape((X.shape[0], X.shape[1], 1))

In [ ]:
X.shape

(9515, 5, 1)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse=False)

# fit encoder to target variable and transform it to one-hot encoding
y_encoded = encoder.fit_transform(y.values.reshape(-1, 1))

print(y_encoded)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.20, random_state=42)

In [ ]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding
from tensorflow.keras.layers import LSTM , Dropout

embedding_vector_features=5

model=Sequential()

#model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))

model.add(LSTM(64,input_shape=(5,1),activation='relu',return_sequences=True))

model.add(Dropout(0.4))

model.add(LSTM(64,activation='relu'))

model.add(Dropout(0.4))

# for units in [128,128,64,32]:

# model.add(Dense(units,activation='relu'))

# model.add(Dropout(0.2))
#model.add(Dense(32,activation='relu'))

model.add(Dropout(0.2))

model.add(Dense(3,activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

print(model.summary())


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 5, 64)             16896     
                                                                 
 dropout (Dropout)           (None, 5, 64)             0         
                                                                 
 lstm_1 (LSTM)               (None, 64)                33024     
                                                                 
 dropout_1 (Dropout)         (None, 64)                0         
                                                                 
 dropout_2 (Dropout)         (None, 64)                0         
                                                                 
 dense (Dense)               (None, 3)                 195       
                                                                 
Total params: 50,115
Trainable params: 50,115
Non-traina

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 5, 64)             16896     
                                                                 
 dropout (Dropout)           (None, 5, 64)             0         
                                                                 
 lstm_1 (LSTM)               (None, 64)                33024     
                                                                 
 dropout_1 (Dropout)         (None, 64)                0         
                                                                 
 dropout_2 (Dropout)         (None, 64)                0         
                                                                 
 dense (Dense)               (None, 3)                 195       
                                                                 
Total params: 50,115
Trainable params: 50,115
Non-traina

In [ ]:
history=model.fit(X_train, y_train, epochs=50, batch_size=32)
# Final evaluation of the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

Epoch 1/50
238/238 [==============================] - 7s 30ms/step - loss: 0.2417 - accuracy: 0.9171
Epoch 2/50
238/238 [==============================] - 3s 11ms/step - loss: 0.2201 - accuracy: 0.9268
Epoch 3/50
238/238 [==============================] - 3s 11ms/step - loss: 0.2237 - accuracy: 0.9330
Epoch 4/50
238/238 [==============================] - 3s 11ms/step - loss: 0.2133 - accuracy: 0.9297
Epoch 5/50
238/238 [==============================] - 3s 11ms/step - loss: 0.2056 - accuracy: 0.9325
Epoch 6/50
238/238 [==============================] - 4s 17ms/step - loss: 0.2015 - accuracy: 0.9351
Epoch 7/50
238/238 [==============================] - 3s 11ms/step - loss: 0.1998 - accuracy: 0.9364
Epoch 8/50
238/238 [==============================] - 3s 11ms/step - loss: 0.1847 - accuracy: 0.9443
Epoch 9/50
238/238 [==============================] - 3s 11ms/step - loss: 0.1869 - accuracy: 0.9423
Epoch 10/50
238/238 [==============================] - 2s 10ms/step - loss: 0.1886 - accura